[theme]
base="light"
primaryColor="#7D5BA6"         # Violet doux
backgroundColor="#dacdebff"      # Fond très clair légèrement lavande
secondaryBackgroundColor="#8d829eff"
textColor="#2E294E"
font="sans serif"
