[theme]
base="light"
primaryColor="#9978c2ff"         # Violet doux
backgroundColor="#e4d5f8ff"      # Fond très clair légèrement lavande
secondaryBackgroundColor="#9e91b3ff"
textColor="#2E294E"
font="sans serif"
